---
apiVersion: v1 
kind: Pod 
metadata: 
  name: myfirstpod 
  labels: 
    app: web
spec:
  containers:
     - name: myfirstcontainer
       image: nginx       
       ports:        
       - containerPort: 80
